# Generated by Django 2.2.6 on 2019-10-06 19:35

import agent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionX', models.FloatField(default=agent.models.randPosition)),
                ('positionY', models.FloatField(default=agent.models.randPosition)),
                ('size', models.FloatField(default=10)),
                ('angle', models.FloatField(default=agent.models.randAngle)),
                ('speed', models.FloatField(default=0.5)),
                ('torque', models.FloatField(default=0.05)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionX', models.FloatField(default=agent.models.randPosition)),
                ('positionY', models.FloatField(default=agent.models.randPosition)),
                ('brightness', models.FloatField(default=0.069)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='agent.Agent')),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='agent.Light')),
            ],
        ),
    ]
